### ISSUE TITLE
3 - Create replica on multiple computers

### ISSUE THREAD

**Issue by ymoisan** [GISeHealth/qgis-versioning#13]
Contract verbatim description : "Geoprocessing tool used to create a replica to a personal, file, or ArcSDE geodatabase from a specified list of feature classes, layers, datasets, and/or tables in an ArcSDE geodatabase"

The terms _replica_, _geodatabase_ and _geoprocessing tool_ relate to ESRI software.  As defined by ESRI, _replicas_ [1] are "the portion of the data in a geodatabase that is copied from a source geodatabase to a destination geodatabase", the geodatabase being "stored in IBM DB2, IBM Informix, Oracle, Microsoft Access, Microsoft SQL Server, and PostgreSQL relational database management systems, or in a system of files, such as a file geodatabase" [2].  In our context, this would mean something like checking out part of a central geodatabase (stored in a relational database server) to a local (personal,file) geodatabase.

A _geoprocessing tool_ is an "ArcGIS tool that can create or modify spatial data, including analysis functions (overlay, buffer, slope), data management functions (add field, copy, rename), or data conversion functions." [3].  In our context, it amounts to a QGIS tool.

The notion of _replica_ amounts to what is referred to as a _checkout_ (PG or spatialite) in the versioning plugin and the local (file) geodatabase amounts to a spatialite file.  The use case here is to allow users to create local copies of arbitrary layers from a central (PostGIS) database with arbitrary features and then commit back their edits to the central database.  That use case that is covered by #9.  

Note : the "3 -" in the title refers to order of importance as previously determined with eHA

[1] http://support.esri.com/es/knowledgebase/GISDictionary/term/replica
[2] http://support.esri.com/en/knowledgebase/Gisdictionary/term/geodatabase
[3] http://support.esri.com/en/knowledgebase/GISDictionary/term/geoprocessing%20tool

**Comment by ymoisan** [comment]
I would be tempted to set as "wontfix"

**Comment by gignacnic** [comment]
We need to test this in a real exercice. For example, if one user do a checkout in a SpatiaLite file and share this checkout Spatialite file with other users and those users are copying this SpatiaLite file locally and use it to edits. Does the commit and update to the common PostGIS database will work as such?

**Comment by Sameme** [comment]
I just test the scenario @gignacnic described earlier today. I had my spatialite checkout in an in-house shared folder on our local server and opened a fresh QGIS Project to access the checkout spatialite (working copy) to try and edit and see if i can still commit it to the Amazon PostGIS but that didn't work, came up with error. I wanted to create a scenario whereby trying to copy/moving the spatialite DB from one folder to another or from one machine to another.

At the moment the plugin only work when the "working copy" (grouped layer) is created on same QGIS Project where you have your initial grouped layer from the Master DB (Amazon PostGIS) and you edit it there for commit. For now you can't move the checkout spatialite from folder to folder or better to say you can't use a fresh QGIS Project to edit a checkout away from the one the working copy was created on. May be part of the reason is because you always have to group the particiapting layers before you can create your checkout

**Comment by ymoisan** [comment]
Hi Sam,

Thanx for trying this.  Can you be more specific about the error ?  I see in the code one error that may occur on groups that are not manageable by the plugin : "The selected group is not a working copy".  Is that what you got ?   

From what I see in the code, the plugin will not recognize as versionable a new group of layers made out of opening an arbitrary spatialite file, even though it was created from a checkout operation, in a new QGIS project.  The information for recognizing a group of layers as a versionable working copy relies on QGIS objects (e.g. layer type, connection string info, etc.).  I don't think that information can be persisted anywhere but in a QGIS project. 

Let's take the problem from a user perspective.  What are you trying to achieve here from a business process point of view ?  What I'm trying to find out is how to best achieve your business process irrespective of how the plugin implements things.  Focusing on trying to share spatialite files (or work collectively on a single network-shared file?) amongst users may turn out to be a non issue if the plugin meets your business requirements with a mixture of code modifications and changes to some eHA  business processes.  I need your lights to understand the business requirements better :-)

**Comment by Sameme** [comment]
Thanks Yves,

I will be describing scenario from our business process point of view. Let say i am the database administrator and i wasn't going to be in the office for a week and i am working offsite. There is the server where i have the master postgis DB, i can easily access it and create checkout as well as commit edit working offsite. Also there is a remote server with a shared folder that my colleagues have access to. I want to create individual "working copy" checkout and for them to go copy their folder containing the checkout to their local machine, do their edit and return the folder back to the shared folder on the remote server where i can commit their individual edits to the Master DB.

What i found out is that this is not possible. When i moved the checkout to my local machine and try to open a new QGIS Project to do my edit, 1. the layers doesn't come as "grouped working copy" anymore and i need them grouped for the plugin to know i want to commit.

I hope my above explanation is a bit clear.

**Comment by ymoisan** [comment]
Thanx for your explanations Samuel.   Can you show me the errors you get ?  I understand you created a spatialite checkout on a network folder.  Copying the spatialite file over to your computer and opening a _new_ QGIS project doesn not allow you to work with the plugin anymore.  Did you try opening the local spsatialite file using the same project you used for the initial checkout ?  I would try this and replace the source of the working copy layers with the local file and see what happens. 

As you have noticed, the plugin creates a new QGIS group called "working copy" where it recopies the layers that were checked out.  Behind the scenes, the plugin fetches the layers/features from the central DB, writes them to a spatialite file (local or network-accessible), creates a new legend group item called "working copy" and creates QGIS layers from the local spatialite file.  Those QGIS objects contain key information that I'm not surprised are not persisted in the spatialite file, so I can see why just creating a bunch of new QGIS objects (groups, layers, etc.) and loading layers from a spatialite file won't have all the information a normal working copy gets.  I don't know if it is possible to somehow share that QGIS-specific information so that users opening a brand new project would load a QGIS project definition and then add layers from their local spatialite file and they would still be able to work with the plugin as if they had done the checkout themselves.

When you say _I want to create individual "working copy" checkout and for them to go copy their folder containing the checkout to their local machine, do their edit and return the folder back to the shared folder on the remote server where i can commit their individual edits_, do I understand some of your colleagues don't -- or are not allowed to -- have access to the database to do the checkouts/commits themselves and therefore you have to do it for them ?  Do you want to create the individual checkouts so you have control of who does what (e.g. users have different sets of layers/features to work on) or are you checking out a "common" file everybody is invited to copy over to their computers and edit parts of ?

**Comment by ymoisan** [comment]
I've tried to picture the actors and uses cases here : https://drive.google.com/open?id=0B1NSVeqvAS8Zd250TVlEUGdCaXM.  Anybody form eHA can edit.  Look for "draw.io" if it isn't the suggested application for editing.  I configured the file so that draw.io opens it when double clicked but I don't know if that's a user-based or document-based preference.

**Comment by Sameme** [comment]
Thanks for your explanation Yves. Now you got the issue i was describing. Also from your explanation you propose a solution that i was thinking about last night. The solution might be that when i create a checkout "working copy", there will be need to save the QGIS Project along with the spatialite, so that once the main folder is moved (copy to another machine) you can just connect and continue........I will try this too today.

Also to clarify, not all editor has access to login detail to the Master DB here. This just to protect the Master DB like in any organisation DB Administration.

Apology, i should have attach the python error screenshot.......i will try the scenario again and attach for you and also checkout draw.io

Great job

**Comment by Sameme** [comment]
I just test the method of saving the "working copy" checkout along side the QGIS Project in the same folder, then moved/copy the folder from a shared folder to my local machine. I opened the QGIS Project everything was retained; the grouped "working copy" checkout. Now i edit the layers and try to commit it but it came up with error. Again i copied this folder from my machine back to the shared folder and open the QGIS Project to commit the edit but it came up with same error.

I have attached the screenshot

Thanks
![moved error](https://cloud.githubusercontent.com/assets/12427102/10689843/d15f4888-7975-11e5-839d-0484e4bd1461.JPG)

**Comment by gignacnic** [comment]
Yes, I got the same kind of message. It looks to QGIS that the SpatiaLite tables are empty with error message in the content of the database. I do not think it will complicated to fix, because this need was in the documentation of Oslandia: edits the SpatiaLite file in a Roaming (mobile) apps: http://www.oslandia.com/qgis-versioning-plugin-en.html , not only directly in the QGIS project running the plugin.

**Comment by ymoisan** [comment]
It's a psycopg error; the connection with PostGIS is refused.  Did you check the layer properties for connection strings ?

**Comment by ymoisan** [comment]
I gave it a try : 
- checked out (a subset) on my Ubuntu laptop; did not do any attribute edits on the sqlite file; saved the project file
- uploaded both the project file (.qgs) and sqlite files on my Google Drive and brought them on a Windows 7 PC
- on Win 7, opened QGIS 2.8 (same version I use on Ubuntu) loaded the project file and : worked !

HINT : the project file (which is really an xml file so you can open it in a regular text editor) shows the layer paths are **relative** to the location of the project file : 

<datasource>dbname='./test-move.sqlite' key='OGC_FID' table="na_bua_sample_polygon_view" (GEOMETRY) sql=</datasource>

What that means is that the sqlite file needs to be copied together with the sqlite files and the latter must be at the same relative location on the new system; when that's respected, you'll see the real path name on Ubuntu (e.g. /home/yvesm/...) and on Windows (e.g. C:\somePath...) QGIS.  The error you had with psycopg (connection to PG) is solved by having the project file.  Weird that it worked for me and not for you ...

I modified the local sqlite file on the Windows machine and committed my changes; success !

Now I had problems trying to bring this all back on my Ubuntu PC.  First I tried just loading my old project (with the unmodified sqlite file).  This triggerred a conflict pop up.  Looks like it's working as it should, but I had weird Python errors when I tried to use the sqlite file I had modified on the Windows machine on Ubuntu.

Anyhow this is too hackish for me.  I'll set up a better test next week.

**Comment by ymoisan** [comment]
To my knowledge this feature is already taken care of via #9.  There may be an additional documentation need to tell users how to edit spatialite files (that is, edit views, not tables), but other than that this issue is fixed.
