### ISSUE TITLE
4 - Add global IDs (UUIDs)

### ISSUE THREAD

**Issue by ymoisan** [GISeHealth/qgis-versioning#14]
Records (features) are to be manageable throughout their life cycles wherever they happen to be edited : central database, local file, etc.  In ESRI land, this calls for a UUID.

The way the plugin works currently ensures features retain a unique ID throughout the editing lifecycle.  I would set this issue as fixed.

Note : the "4 -" in the title refers to order of importance as previously determined with eHA

**Comment by gignacnic** [comment]
This is supported by primary key unique id in postgresql and already supported in the plugin.
