### ISSUE TITLE
Adapt checkout for team work

### ISSUE THREAD

**Issue by ymoisan** [GISeHealth/qgis-versioning#18]
The _revisions_ table currently has 5 fields : rev, commit_msg, branch, date, author 

The _author_ is taken as the user_name [1] of the committer.  In the case where a person is in charge of reviewing and integrating editor sqlite files, for example, the name of that original editor is lost because it is the committer's name (the coordinator) that will be stored in the _author_ field.

For a team of people with different access rights to the database and working with spatialite checkouts, we need to add additional fields in the _revisions_ table to cater for the case where the person committing in the central DB is not the same as the original spatialite editor.  How to do that is discussed below.

**Current inclination** maybe a specific implementation of checkout could be done for so-called "team checkouts" ?  The person responsible for checkouts would have the opportunity to choose the name of the editor (in a list of PG users; so that implies all editors have at least read-only accounts in PG) as the very first step of the checkout process; this would write the PG userame in some sqlite table (TBD) and the filename would get the name of the user appended somewhere in it's name so the coordinator knows who to send the file to.  

That "team_checkout" implementation would optionally allow to load the file in a QGIS layer group or not since the coordinator may checkout the same file for many different editors.  Once the spatialite files are sent back to the coordinator, the latter commits the changes.  The revisions table needs to store information about the actual person that edited the file together with who is committing the modified file to the central DB.  Additional info may require : 
- pg username of editor (already in the original checkout, as explained above)
- pg username of coordinator (committer)
- specific information on coordinator's device (OS type/version, version of plugin, MAC address ?)
- etc

For auditing purposes, we understand the business process is important, for example to ensure that a file sent to a specific editor effectively gets modified by that person.  There is no way to ascertain that with spatialite files to our knowledge (unless we find some way to insert device specific info in the spatialite file).

[1] The code used is getpass.getuser(), which returns the “system login name” (not the PG username, but the operating system username) of the user (see https://docs.python.org/2/library/getpass.html)

**Comment by gignacnic** [comment]
Since in some cases, the GIS coordinator who will be in charge of the commit would not be the "author" for real, it would be interested to keep in the commit the real Editor author value. An option when committing that could be added in a checkbox option is to change the author default value, since in this case, the author is not the login name. So that is why we can considered the GIS coordinator who commit as the validator and not the author, the GIS coordinator would need to select the author from the list of pguser in the PostGIS main head database using: "select usename from pg_user" in the background and the GIS coordinator (validator) would choose the author-editor user name from this list. Other options can be assess to see how this information can stored in the SpatiaLite, but it might need to be implemented outside the plugin.

**Comment by gignacnic** [comment]
A mechanism of checkout and update permission type of user in PostGIS can be also discussed.

**Comment by ymoisan** [comment]
Thinking about it, I am not sure the revisions table should have another field.  What that table stores really is who the committer is (author) and when the commit was done (date).  This has only an indirect relation to specific feature editing dates and author names since the commit applies in bulk to all edits, regardless of the fact that some of those edits may have been further edited by the committer prior to committing.

Seems to me that additional attributes relating to editing time and author should be done at the feature level, since that is where editing attributes belong rather than in the revisions table.

**Comment by gignacnic** [comment]
I think that like a pull request and merge request is done in GitHub, it is important to keep who has propose the original edits and who commit (or merge) the edits to the head revision. So the author who be the person who fork and edits and the validator would be the person who commit and merge the request. Does it make sense? It would be more complex to implement the logic at the feature level.

**Comment by ymoisan** [comment]
The analogy is good.  The pull request (PR) in our case simply amounts to an editor sending a spatialite file to a reviewer and asking for a merge and commit.  

One problem I see is that there are a lot of manual bits and pieces in the process.  In a GH context, commits pertaining to a PR are all authored by virtue of GH credentials so both granularity (who committed all code changes included in the PR) and traceability are ensured.  Allowing a reviewer to add the name of an author prior to committing opens the question of what names can be added. 

There is no way the plugin can enforce a list of author names.  All it does now is retrieve the username of the person who has the current QGIS session and that's all it can do really.  It could leave the door open to customization (e.g. by allowing a query for a list of users in the PG backend) but I consider this is outside the plugin's scope.  IMO the plugin cannot provide a sensible default value other than the current username.   It could pop a free text field for the committer to fill if (s)he is not also the editor If we can live with the potential for errors this brings about.  But I guess we need to rely on an organization's business processes here.  Manual interventions just imply stricter business processes.

**Comment by gignacnic** [comment]
I have thought about another process, once the GIS coordinator is doing a checkout, the plugin can give an option to assign this checkout to a username. The value selected by the Coordinator from "select usename from pg_user" is stored in the SpatiaLite database (and can be given in the SpatiaLite file name) and once an Editor give back this SpatiaLite file to the Coordinator, automatically this author-validator value is given during the commit? What do you think?

**Comment by ymoisan** [comment]
Interesting.  It's better in terms of automation but the reliability of the info is still highly dependent on the business process.  Coordinator checks out file for Editor A, so he selects Editor A's name which gets stuck in some spatialite table/field.  First, a list of pg_users restricts who editors may be.  If they happen to have a username in PG all the better, but what if not ?  And odds are a lot of editors, who can be regular employees or consultants, may not have an entry in pg_user.  Second, when that file is sent to Editor A, nothing stops him from passing the file on to Editor B etc.  Also, what if the coordinator checks out the same file for many editors ?

At least we have a field in a file we can use (better for automation), but the accuracy of the information is very hard to ascertain.  It all boils down to the level of traceability an organization needs.  In our context, traceability implies "who edited feature X at revision Y" and "who committed/reviewed" the work.  The plugin currently only ensures traceability of the latter.

**Comment by gignacnic** [comment]
OK, we could assess this:  http://stackoverflow.com/a/1830635, because it seems that we could get the owner of a SpatiaLite file (copy & paste on a network by an Editor once he finished his edits and ready to be committed) with python, this value can be different from the actual author value (local login name) used in the plugin: https://docs.python.org/2/library/getpass.html.
If it does work, we could check this owner SpatiaLite file value compared to the other local computer login name (author), if it is very different, we can alert the committer (GIS Coordinator) and he could decide to do a commit with different value for validator-author or consider himself as the validator AND author.

**Comment by ymoisan** [comment]
The link you are pointing to implies the use of the *pwd* python module, which does not work on MS Windows.  Plus, I don't think we'd get more info than getpass because once the file is written on the filesystem it takes the new owner's name which is the same identifier as the logged in username.  So in effect getpass does what we want, except we need to keep the information in the spatialite file (e.g. history of edits) before it is passed around.

**Comment by gignacnic** [comment]
OK, I did not check in the Availability section that Windows was not supported, but if the SL file is stored in a shared network it would have been be available. I saw this, but it looks complicated in Windows to get this user id: http://stackoverflow.com/questions/3305787/what-is-the-windows-equivalent-of-pwd-getpwnamusername-pw-dir. So, I think it would have to be implement into the PostGIS database process.

**Comment by vmora** [comment]
+1 for me

**Comment by vmora** [comment]
Just wondering why you need to identify the coordinator device.

Also, you can use encryption software on the .sqlite file to make sure that only the editor as acces to it, and have the coordinator receive en encrypted .sqlite file that will be decoded with the user public key (gpg).

**Comment by ymoisan** [comment]
@vmora : thanx for your comments.  The whole point here is that we want as much info for auditing purposes as possible.  Currently, if I commit from my Ubuntu machine the revisions table will show a different author name than if I commit from my windows machine because it so happens my usernames on those machines are different.  Two different persons ?  Obviously no so we need the pg user identifier to identify who has committed.  

I think committer device info, which is indirectly what we have now with the plugin, would be useful information to have from an auditing perspective. We'd get the who (pg_user), when (timestamp), what (revision number), where (device info) in case someone needs to trace back an issue with the commit.  Almost the [Five W's ](https://en.wikipedia.org/wiki/Five_Ws).  Ideally, I would have liked to have those W's for the editor too to be able to trace issues with the **data** related to the commit but that's a harder call.  Just having the who and where for the user would be enough I think.  That way an auditor would be able to trace back an issue with data (accidental/deliberate corruption, etc.) with the set of W's for the coordinator and the editor.  Of course that won't tell us if the coordinator further edited features that the editor sent but this is a risk that I think can now be taken and can be mitigated by strict business processes, e.g. coordinator only allowed to commit and resolve conflicts (no further editing before committing).

Thanx for your suggestion of encrypting the file.  It obviously restricts people other than the original editor from tampering with the data.

**Comment by ymoisan** [comment]
Proposal by Nicolas and myself : we will not add an extra field to the revision table.  Instead, we will use the current author field but append the pg_user information in the existing string : system_username.pg_user, where system_username is what is currently stored in the author field and pg_user will default to the current pg username of the coordinator.  On commit, the coordinator will be prompted to change the pg_user if the actual editing work was done by another user.

This means that individual editors must have at least read-only user accounts in PG.

**Comment by ymoisan** [comment]
A first pass is in the _temwork_ branch : abb91ab.  Result is that the _author_ field in the _revisions_ table now has : 

> os_info:committer_os_username.committer_pg_user.editor_pg_user

instead of what it contains currently : 

> committer_os_username

A new dropdown list (combobox) was added to the commit dialog.  The committer may select the corresponding pg_username of the editor.  Default value = pg_username of the committer.

**Comment by ymoisan** [comment]
To do : initialize more of the the combobox-related dialog layout in the Versioning class (self.q_commit_msg_dlg) rather than directly in versioning.commit.  This will in turn allow to : 
- disable the combobox for versioning.pg_commit 
- edit the dialog behaviour in versioning.branch

**Comment by ymoisan** [comment]
Done in d26ec4d
- Disabled combobox for branch (wasn't needed for pg_commit).
- Added descriptive text label for the dropdown in the QComboBox and tooltip info

**Comment by ymoisan** [comment]
Done in d26ec4d
- Disabled combobox for branch (wasn't needed for pg_commit).
- Added descriptive text label for the dropdown in the QComboBox and tooltip info

**Comment by ymoisan** [comment]
I have reverted to the way I did it earlier, that is populate the combobox in versioning.commit but this time I'm calling a method instead.  See a11a464.

@vmora : I'm not happy with having to check if the combo is populated on every versioning.commit.  If I don't check, then the combo gets N times the list of users.  I was thinking I could fill the combo once at plugin startup to avoid the unnecessary check so I tried initGui, but that's too early.  Do you have a suggestion ?  Otherwise I think we can live with the if, as commits won't be that numerous for any one user session.  It's just not optimal.  Thanx in advance and Happy New Year !

**Comment by vmora** [comment]
There is a signal QgsMapLayerRegistry.instance().layersAdded emitted when layers are added and another when projet file is read QgsProject.instance().readProject, you can hook up to one of those in initGui.

**Comment by ymoisan** [comment]
@vmora : Thanx.  What if QGIS is started "clean", that is no layer (and therefore no project) yet ?  I often start QGIS without a project (all the times in Windows since I double-click the QGIS Desktop icon rather than launch qgis from the commandline with a project name as an argument).  In that (general) case neither layersAdded nor readProject signals would be emitted so the combo wouldn't be initialized.  Since initGUI is done only once at load time (?) then the combo would remain unfilled even if I load layers or a project after QGIS was launched.  Am I right ?

If there is no way to simply say "fill the combo on either the first PG layer loaded or project loaded event" (and not have to bother dismissing other events of that type with some sort of _if_), I'll just leave things as they are now, that is initialize the combo in the commit function.  Are you OK with that ?

**Comment by vmora** [comment]
Well, you certainly have to test the layer type and availability of versionning in your "layersAdded" hook. The combo box cannot be filled before that anyway.

**Comment by ymoisan** [comment]
Thank you for your answer.  I just think that for the general use case of people launching QGIS without a project initGUI would execute without having the chance to get either signal so I'm back to square 1.  If QGIS is opened with a project, then I can use initGUI; else I have to do it some other place and I don't see where else than in the commit method for now.  Unless I can somehow suspend initGUI until the user loads a project/layer ?  Looks like quite a management hassle.
