### ISSUE TITLE
Show revisions in diff format

### ISSUE THREAD

**Issue by ymoisan** [GISeHealth/qgis-versioning#25]
Currently, the "view" icon allows one to select a revision and show it in a QGIS layer group.  It would be useful from a history management point of view to add a comparison mode to allow users to select two revisions and show differences between the two (e.g. similar features in black, features in rev X in color X and features in rev Y in color Y)

**Comment by ymoisan** [comment]
Ideas : 
- allow users to view one or many individual revisions with the full set of data (current behaviour); the user could check any number of revisions he wants; I added checkboxes for that on our [view branch](https://github.com/GISeHealth/qgis-versioning/tree/view)
- allow "diff mode" views; if that mode is selected (checkbox in the view dialog?), then only 2 revisions can be selected and the older one becomes rev_begin; some DB object would be passed rev_begin and rev_end and would be responsible for sending the diff (set of features) back to the python code; an extra attribute to identify the type of edit (modified | deleted | added) needs to be appended to those features so that styling can be done based on that attribute in a QGIS vector layer (whichever provider we choose for the vector layer; I was thinking maybe the memory provider).  End result would be a single vector layer with "color-coded" features showing the difference.

One issue we see with the current implementation is the need to create a new schema to hold the view for the revision.  We already have branching creating additional schemas.  Do we really need to create a schema for views too ?

**Comment by ymoisan** [comment]
1) load view layers in a vector memory layer; implies no more schemas created in PG

2) implement "diff mode" : checkbox in view window that becomes selectable when two revisions are checked; if user checks, a layer with color-coded features appears; if after setting "diff mode" the number of layers != 2, diff mode is disabled (grayed out).  Even if it was previously ticked, it is disabled thus the user gets N layers with the full set of features (no colors).

**Comment by gignacnic** [comment]
Here is the query I proposed in order to get the diff_status before loading the memory layer, it should look like (where lw_vers is lower version and up_vers is upper version and diff_status field is what you should use for color-coded of diff mode):
SELECT 
    *,
    CASE 
-- ADD
    WHEN schema.table_name.trunk_rev_begin > lw_vers AND schema.table_name.trunk_rev_begin <= up_vers AND schema.table_name.trunk_parent IS NULL THEN 'a'
-- UPDATE
    WHEN schema.table_name.trunk_rev_begin > lw_vers AND schema.table_name.trunk_rev_end IS NULL AND schema.table_name.trunk_parent IS NOT NULL THEN 'u'
-- DELETE
    WHEN schema.table_name.trunk_rev_end > lw_vers AND schema.table_name.trunk_rev_end <  up_vers AND schema.table_name.trunk_child IS NULL THEN 'd'
    END as diff_status
   FROM schema.table_name
  WHERE (schema.table_name.trunk_rev_begin > lw_vers  AND schema.table_name.trunk_rev_begin <=  up_vers) OR (schema.table_name.trunk_rev_end > lw_vers AND schema.table_name.trunk_rev_end < up_vers AND schema.table_name.trunk_child is NULL);

Try this and let me know.

**Comment by ymoisan** [comment]
One issue is that versioned databases with more than the default **trunk** branch won't be properly processed by the query.  Looking only at trunk_\* (where \* = rev_begin, rev_end, parent, child) and not at other branches_\* won't give the whole picture.  For this to work, we need to somehow refrain users from creating branches other than the default and/or we specifically mention diff mode is only applicable to the **trunk** branch.

**Comment by ymoisan** [comment]
UI functionnality implemented (4bf8def).  When the dialog pops, the _Diff mode_ checkbox is disabled (no revision is checked): 

![fresh](https://cloud.githubusercontent.com/assets/7468595/12334841/4195b6f6-baca-11e5-9da2-ae82d2d0d8ba.png)

When any two revisions are selected, the checkbox is enabled for the user to check (or not) : 

![2-revs](https://cloud.githubusercontent.com/assets/7468595/12334858/53e78974-baca-11e5-8484-6bfd8216d7c5.png)

If the user selects/deselects revisions after having set the _Diff mode_ checkbox, it is unchecked and disabled because the number of selected revisions is not two anymore : 

![uncheck](https://cloud.githubusercontent.com/assets/7468595/12334969/c5270b6e-baca-11e5-8ab0-74b5a66c9f7e.png)

It can only be re-enabled when two revisions are selected.

Functional implementation remains to be done.  Current behaviour is to display a message box in the main QGIS window : 

![info-msg-diff-mode](https://cloud.githubusercontent.com/assets/7468595/12334768/c7578a72-bac9-11e5-8b71-a746cb3ca6be.png)

**Comment by ymoisan** [comment]
Oslandia#37 solved this issue
