### ISSUE TITLE
Large feature selection size causes no filtering

### ISSUE THREAD

**Issue by ymoisan** [GISeHealth/qgis-versioning#26]
When one is selecting a large number of features from a layer in a versioned database (around 5000 +) prior to doing a spatialite checkout, the plugin does not show the expected pop up ("You will be checking out the subset of N features ...").  Instead, it checks out the whole layer as if no selection were supplied.

**Comment by Sameme** [comment]
Recently i have been testing with a larger data on my local machine (laptop) to simulate how eHA it will look like when we finally deploy and noticed this error along with Yves. Out of over 150,000 points record i was trying to checkout close to 10,000 but realise since the point records was much the plugin decided to checkout all the 150,000 records. But it work fine with the polygon which was just over 300 records. I have attached a screenshot of my selection before checkout and my result checkout.
![borno_shot](https://cloud.githubusercontent.com/assets/12427102/11563903/974d407e-99d6-11e5-98d5-920a8c87f785.JPG)

Result
![borno_2](https://cloud.githubusercontent.com/assets/12427102/11563915/ad828bba-99d6-11e5-8a2e-704b651477c2.JPG)

**Comment by Sameme** [comment]
Again trying to checkout somewhat intermediate size of 4,000 points, the plugin throw-up this error. Screeshot is added below
![borno_3](https://cloud.githubusercontent.com/assets/12427102/11564092/80327b56-99d7-11e5-99bd-3f83cb7eff04.JPG)

**Comment by ymoisan** [comment]
OK so here is a wrap up of this issue : 

1) QGIS has a bug with fetching feature attributes when the list of features is large; this is irrespective of operating system.

2) To address 1), we used a method (selectedFeaturesIds) that requires that the PK field of the datasource (which can point to a real PG table or to a view, as is our case when the database is versioned) matches that of the table.

After fixing those problems, we came across the issue of the limitations of the Windows commandline.  As explained [here](https://support.microsoft.com/en-us/kb/830473), "On computers running Microsoft Windows XP or later, the maximum length of the string that you can use at the command prompt is 8191 characters".  

The way the checkout in a spatialite file is created involves calling the ogr2ogr system command through Python's os.system().   Before implementing feature selection on checkouts, the ogr2ogr command was fairly small (no _where_ clause).  With the new implementation, where we add _ids_ of selected features in a _where_ clause, the length of the command increases with the number of selected features and there comes a point where it is too long and does not work on Windows.  FYI, I saw 100 000 + characters in some of our ogr2ogr commands ...

We tried replacing the way Python calls system executables, that is replace os.system() with subprocess.call(), but our tests have not revealed a way around the Windows limitations.

Options we have (short of running checkout operations on Linux or Mac) : 
- install GDAL 2.1 to get the ogr2ogr command with the possibility to specify a file in the _where_ clause (see [here](http://www.gdal.org/ogr2ogr.html) and search "-where"); this is what Microsoft proposes : "To work around the limitation ... Modify programs that require long command lines so that they use a file that contains the parameter information" (same url as above).  This is a cumbursome solution as it would impose a custom setup on user computers.  Also, it would be unacceptable to require that users of the plugin in Windows have GDAL 2.1+ installed
- refactor the plugin so that it uses the [ogr Python bindings](https://pcjericks.github.io/py-gdalogr-cookbook/) instead of system calls; this implies some work
- use a temporary PG view; that's what the plugin does in certain circumstances so that's what we will implement for now

**Comment by ymoisan** [comment]
Using the temporary view brought about another issue : the preserve_fid behaviour of the ogr2ogr command is lost when building the view with a **" select \* "** statement.  We have to call each column by name in the SELECT clause in order to replace the pkey with "pkey AS OGC_FID", which preserves fid.  See 109c484

@vmora : are you OK wih that ?  If so, I will wait for formal acceptance tests, rebase and ask you to include the PR.

**Comment by vmora** [comment]
+1 for explicit column spec.
