### ISSUE TITLE
Spatialite Checkout error

### ISSUE THREAD

**Issue by Sameme** [GISeHealth/qgis-versioning#38]
Spatialite checkout is not working with the plugin. Coming up with this python error below

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\qgis_versioning\versioning.py", line 953, in checkout
    tables_for_conninfo, filename, user_selected_features )
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\qgis_versioning\versioning_base.py", line 391, in checkout
    "AND "+branch+"_rev_begin IS NOT NULL")
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\qgis_versioning\versioning_base.py", line 152, in execute
    self.cur.execute( sql )
OperationalError: near "FROM": syntax error

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

I am also attaching the screenshot of the error.
![error2 8](https://cloud.githubusercontent.com/assets/12427102/19128011/59485f0c-8b39-11e6-964a-5d3d6445e31a.JPG)

@vmora @DamiSonoiki

**Comment by gignacnic** [comment]
Would it be related to this previous issue: https://github.com/GISeHealth/qgis-versioning/issues/35

**Comment by Sameme** [comment]
I am not too sure it will be that. This has nothing to do with the file name

**Comment by vmora** [comment]
do you have spaces in the table name ?

**Comment by Sameme** [comment]
No. There isn't space in the table name

**Comment by vmora** [comment]
could you try adding a default log file in the **init** function of Db in versionning_base.py:
replace:

```
    def __init__(self, con, filename = ''):
```

by 

```
    def __init__(self, con, filename = 'mylog.txt'):
```

then reproduce and attach the log.

**Comment by Sameme** [comment]
OK.....I will get back.

**Comment by Sameme** [comment]
I change the code line 
![changeline](https://cloud.githubusercontent.com/assets/12427102/19149372/7038247e-8bb9-11e6-97dc-f46c6c4aebee.JPG)

But I am getting this error once i click the spatialite checkout logo on the UI

![changedlinerror](https://cloud.githubusercontent.com/assets/12427102/19149464/c7153796-8bb9-11e6-9552-08719ae04cc0.JPG)

**Comment by vmora** [comment]
Because qgis is launched from a directory you cannot write to, you can specify a file with an absolute path:
"C:/Users/your_name/..."

**Comment by ayodeleadeyemo** [comment]
Based on @Sameme's last issue, Try to run QGIS as an administrator.

**Comment by femtope** [comment]
Also when checkout in either spatialite or postgis, the file path to write to must be without space.

**Comment by femtope** [comment]
The spatialite checkout is work perfectly ok for now. 
1. Run your qgis as an administrator.
2. Make sure the filepath you are saving your checkout is without a space.
Thanks
