### ISSUE TITLE
unique id integer in trunk head in view needs to be unique , if not invalid layer

### ISSUE THREAD

**Issue by gignacnic** [GISeHealth/qgis-versioning#7]
Once you create a versioning of layers selected in QGIS in a new trunk_head schema, and when you add those layers back using DB-Manager or "add layer" menu, this error message comes up: "sql= is an invalid layer and cannot be loaded"...QGIS always uses the first integer field in the view (SELECT) as unique id once he try to add layer in its map window.

**Comment by gignacnic** [comment]
so, if the first integer field of the view (in the SELECT) of alla layers in trunk_head, it's field order needs to be change to be able to get rid of this error message: "sql= is an invalid layer and cannot be loaded", so a fix is: it to put the unique id (primary key) of the table as the first field in the view SELECT in the trunk_head.

**Comment by ymoisan** [comment]
test

**Comment by ymoisan** [comment]
Test closing.  Does it show up as "Done" in overv.io ?
