### ISSUE TITLE
if ogc_fid field should not exist before using versioning plugin

### ISSUE THREAD

**Issue by gignacnic** [GISeHealth/qgis-versioning#8]
If you use a table which has already a field named: "ogc_fid" (which is always created by ogr2ogr when importing and exporting), this table cannot be properly in the egis versioning plugin.

**Comment by gignacnic** [comment]
So, the best way to fix this problem is to drop all columns called ogc_fid: 
ALTER TABLE schema.tablename DROP COLUMN ogc_fid;
 of all tables that you want to use in the versioning plugin.

**Comment by ymoisan** [comment]
test

**Comment by ymoisan** [comment]
Test closing.  Does it show up as "Done" in overv.io ?
